const icons = {
    logo: require('./logo.svg').default,
    arrow: require('./assets/icons/arrow.svg').default,
    camera: require('./assets/icons/camera.svg').default,
    expired: require('./assets/icons/expired.svg').default,
    hamburger: require('./assets/icons/hamburger.svg').default,
    help: require('./assets/icons/help-circle.svg').default,
    hide: require('./assets/icons/hide.svg').default,
    home: require('./assets/icons/home.svg').default,
    logout: require('./assets/icons/logout.svg').default,
    notification: require('./assets/icons/notification.svg').default,
    remove: require('./assets/icons/remove.svg').default,
    search: require('./assets/icons/search.svg').default,
    setting: require('./assets/icons/setting.svg').default,
    show: require('./assets/icons/show.svg').default,
    tick: require('./assets/icons/tick.svg').default,
    upload: require('./assets/icons/upload.svg').default,
    xIcon: require('./assets/icons/x-icon.svg').default,
    loading: require('./assets/icons/loading-progress.png').default,
}
export default icons
